apiVersion: skaffold/v4beta2
kind: Config
build:
  # googleCloudBuild:
  #   projectId: tick-397513
  local:
    push: false
  tagPolicy:
    sha256: {}
  artifacts:
    - image: justin8888/auth
      # - image: asia.gcr.io/tick-397513/auth
      context: auth
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: justin8888/client
      # - image: asia.gcr.io/tick-397513/client
      context: client
      sync:
        manual:
          - src: '**/*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: justin8888/tickets
      # - image: asia.gcr.io/tick-397513/tickets
      context: tickets
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: justin8888/orders
      # - image: asia.gcr.io/tick-397513/orders
      context: orders
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: justin8888/expiration
      # - image: asia.gcr.io/tick-397513/expiration
      context: expiration
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: justin8888/payments
      # - image: asia.gcr.io/tick-397513/payments
      context: payments
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
