apiVersion: apps/v1
kind: Deployment
metadata:
  # annotations:
  # cloud.google.com/app-protocols: '{"auth":"HTTP2"}'
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          # image: justin8888/auth
          image: asia-southeast1-docker.pkg.dev/ticket-396008/ticket/auth
          # ports:
          #   - containerPort: 3000
          env:
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/auth'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
